/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai3;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        kiemtraIP = new javax.swing.JMenuItem();
        timipcuatenmien = new javax.swing.JMenuItem();
        timtenmiencuaip = new javax.swing.JMenuItem();
        TimIpmaycucbo = new javax.swing.JMenuItem();
        Kiemtradacdiemip = new javax.swing.JMenuItem();
        Kiemtra2tenmien = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Hệ thống");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng");

        kiemtraIP.setText("Kiểm tra IP");
        kiemtraIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiemtraIPActionPerformed(evt);
            }
        });
        jMenu2.add(kiemtraIP);

        timipcuatenmien.setText("Tìm IP của tên miền");
        timipcuatenmien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timipcuatenmienActionPerformed(evt);
            }
        });
        jMenu2.add(timipcuatenmien);

        timtenmiencuaip.setText("Tìm tên miền của IP");
        timtenmiencuaip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timtenmiencuaipActionPerformed(evt);
            }
        });
        jMenu2.add(timtenmiencuaip);

        TimIpmaycucbo.setText("Tìm IP của máy cục bộ");
        TimIpmaycucbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimIpmaycucboActionPerformed(evt);
            }
        });
        jMenu2.add(TimIpmaycucbo);

        Kiemtradacdiemip.setText("Kiểm tra đặc điểm IP");
        Kiemtradacdiemip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiemtradacdiemipActionPerformed(evt);
            }
        });
        jMenu2.add(Kiemtradacdiemip);

        Kiemtra2tenmien.setText("Kiểm tra 2 tên miền");
        Kiemtra2tenmien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kiemtra2tenmienActionPerformed(evt);
            }
        });
        jMenu2.add(Kiemtra2tenmien);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timtenmiencuaipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timtenmiencuaipActionPerformed
       TimtenmiencuaIP ip= new TimtenmiencuaIP();
       ip.show();
       this.dispose();
    }//GEN-LAST:event_timtenmiencuaipActionPerformed

    private void timipcuatenmienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timipcuatenmienActionPerformed
        TimIPcuatenmien ip = new TimIPcuatenmien();
        ip.show();
        this.dispose();
    }//GEN-LAST:event_timipcuatenmienActionPerformed

    private void TimIpmaycucboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimIpmaycucboActionPerformed
        TimIpcuamaycucbo ip = new TimIpcuamaycucbo();
        ip.show();
        this.dispose();
    }//GEN-LAST:event_TimIpmaycucboActionPerformed

    private void kiemtraIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiemtraIPActionPerformed
        KiemtraIP kt = new KiemtraIP();
        kt.show();
        this.dispose();
    }//GEN-LAST:event_kiemtraIPActionPerformed

    private void KiemtradacdiemipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiemtradacdiemipActionPerformed
        KiemtradacdiemIP ip = new KiemtradacdiemIP();
        ip.show();
        this.dispose();
    }//GEN-LAST:event_KiemtradacdiemipActionPerformed

    private void Kiemtra2tenmienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kiemtra2tenmienActionPerformed
        Kiemtra2tenmien kt = new Kiemtra2tenmien();
        kt.show();
        this.dispose();
    }//GEN-LAST:event_Kiemtra2tenmienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Kiemtra2tenmien;
    private javax.swing.JMenuItem Kiemtradacdiemip;
    private javax.swing.JMenuItem TimIpmaycucbo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem kiemtraIP;
    private javax.swing.JMenuItem timipcuatenmien;
    private javax.swing.JMenuItem timtenmiencuaip;
    // End of variables declaration//GEN-END:variables
}
